package com.fongmi.android.tv.theme;

/** Immutable Material 3 semantic color and player-control contract. */
public record ThemeTokens(
        int colorPrimary,
        int colorOnPrimary,
        int colorPrimaryContainer,
        int colorOnPrimaryContainer,
        int colorSecondary,
        int colorOnSecondary,
        int colorSecondaryContainer,
        int colorOnSecondaryContainer,
        int colorTertiary,
        int colorOnTertiary,
        int colorError,
        int colorOnError,
        int colorErrorContainer,
        int colorOnErrorContainer,
        int colorSuccess,
        int colorOnSuccess,
        int colorSuccessContainer,
        int colorOnSuccessContainer,
        int colorWarning,
        int colorOnWarning,
        int colorWarningContainer,
        int colorOnWarningContainer,
        int colorSurface,
        int colorSurfaceDim,
        int colorSurfaceBright,
        int colorSurfaceContainerLowest,
        int colorSurfaceContainerLow,
        int colorSurfaceContainer,
        int colorSurfaceContainerHigh,
        int colorSurfaceContainerHighest,
        int colorOnSurface,
        int colorOnSurfaceVariant,
        int colorOutline,
        int colorOutlineVariant,
        int colorInverseSurface,
        int colorInverseOnSurface,
        int colorInversePrimary,
        int colorScrim,
        int colorShadow,
        int colorFocus,
        float focusScale,
        float dialogOpacity,
        int colorPlayerControl,
        int colorPlayerControlMuted,
        int colorPlayerControlActive,
        int colorPlayerScrim,
        int colorHealthGood,
        int colorHealthWarn,
        int colorHealthBad,
        int colorOverlayLight,
        int colorOverlayDark
) {

    public static ThemeTokens light() {
        return new ThemeTokens(
            0xFF0B57D0,
            0xFFFFFFFF,
            0xFFD3E3FD,
            0xFF041E49,
            0xFF5B5F63,
            0xFFFFFFFF,
            0xFFDFE2E6,
            0xFF191C1E,
            0xFF00639B,
            0xFFFFFFFF,
            0xFFB3261E,
            0xFFFFFFFF,
            0xFFF9DEDC,
            0xFF410E0B,
            0xFF146C2E,
            0xFFFFFFFF,
            0xFFC4EED0,
            0xFF00210B,
            0xFF7A5900,
            0xFFFFFFFF,
            0xFFFFDF9A,
            0xFF261A00,
            0xFFF8FAFD,
            0xFFD8DAE0,
            0xFFF8FAFD,
            0xFFFFFFFF,
            0xFFF2F3F9,
            0xFFECEEF4,
            0xFFE7E8EF,
            0xFFE1E2E9,
            0xFF1A1C1E,
            0xFF44474F,
            0xFF74777F,
            0xFFC4C6CF,
            0xFF2F3033,
            0xFFF1F0F4,
            0xFFA8C7FA,
            0x52000000,
            0xFF000000,
            0xFF0B57D0,
            1.0f,
            1.0f,
            0xFFFFFFFF,
            0xCCFFFFFF,
            0xFFFFD35C,
            0x7A000000,
            0xFF146C2E,
            0xFF7A5900,
            0xFFB3261E,
            0x14FFFFFF,
            0x52000000
    );
    }

    public static ThemeTokens dark() {
        return new ThemeTokens(
            0xFFA8C7FA,
            0xFF062E6F,
            0xFF0842A0,
            0xFFD3E3FD,
            0xFFC6C6C9,
            0xFF2F3133,
            0xFF44474A,
            0xFFE2E2E6,
            0xFF8ECDFF,
            0xFF003353,
            0xFFFFB4AB,
            0xFF690005,
            0xFF93000A,
            0xFFFFDAD6,
            0xFF8EDB9F,
            0xFF003918,
            0xFF00522A,
            0xFFC4EED0,
            0xFFF2C66D,
            0xFF402D00,
            0xFF5C4200,
            0xFFFFDF9A,
            0xFF101418,
            0xFF0B0E11,
            0xFF363A3F,
            0xFF0B0E11,
            0xFF181C20,
            0xFF1F2428,
            0xFF2A2F34,
            0xFF34393E,
            0xFFE2E2E9,
            0xFFC4C6D0,
            0xFF8E9099,
            0xFF44474F,
            0xFFE2E2E9,
            0xFF2F3033,
            0xFF0B57D0,
            0x8A000000,
            0xFF000000,
            0xFFA8C7FA,
            1.1f,
            1.0f,
            0xFFFFFFFF,
            0xCCFFFFFF,
            0xFFFFD35C,
            0x8F000000,
            0xFF8EDB9F,
            0xFFF2C66D,
            0xFFFFB4AB,
            0x14FFFFFF,
            0x66000000
    );
    }

    public ThemeTokens requireContrast() {
        ThemeContrast.require(this);
        return this;
    }
}
